language: c
dist: trusty

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
  - sudo apt-get -q update
  - sudo apt-get -y install libgmp-dev
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack update
  - stack --no-terminal setup
  

install:
  - stack build


script:
  - stack --no-terminal --skip-ghc-check test
